main: aliuly\worldprotect\Main
api: [1.10.0,1.12.0]
load: STARTUP

name: WorldProtect
description: protect worlds from griefers, pvp, limits and borders
version: 2.2.0
author: aliuly
website: https://github.com/alejandroliu/pocketmine-plugins/tree/master/WorldProtect

commands:
  worldprotect:
    description: Manage worlds
    usage: "/sc <help|sub-cmd> [options]"
    permission: sc.cmd.all
    aliases: [Security]

permissions:
  sc.motd:
    default: true
    description: "Display MOTD"
  sc.cmd.all:
    default: op
    description: "Allow access to protect command"
  sc.cmd.protect:
    default: op
    description: "Change protect mode"
  sc.cmd.protect.auth:
    default: op
    description: "Permit place/destroy in protected worlds"
  sc.cmd.border:
    default: op
    description: "Allow contfol of border functionality"
  sc.cmd.pvp:
    default: op
    description: "PvP erlauben"
  sc.cmd.noexplode:
    default: op
    description: "Allow NoExplode controls"
  sc.cmd.limit:
    default: op
    description: "Allow control to limit functionality"
  sc.cmd.wpmotd:
    default: op
    description: "Allow editing the motd"
  sc.cmd.addrm:
    default: op
    description: "Allow modifying the auth list"
  sc.cmd.unbreakable:
    default: op
    description: "Modify unbreakable block list"
  sc.cmd.bancmd:
    default: op
    description: "Ban/unban kommands"
  sc.cmd.banitem:
    default: op
    description: "Ban/unban items"
  sc.cmd.info:
    default: true
    description: "Show WP config info"
  sc.cmd.gm:
    default: op
    description: "Allow setting a per-world gamemode"
  sc.cmd.gm.exempt:
    default: false
    description: "Users with this permissions will ignore per world gm"
